import java.io.*;
import java.util.*;

/**
 * This class reads the output files generated by NovelProcessor, aggregates the counts
 * of each pattern across all novels, and prints the final count for each pattern.
 *
 * @author Jaleah Beason
 * @version 1.0
 * Assignment 4
 * CS322 - Compiler Construction
 * Spring 2024
 */
public class WordCounter {

	 /**
     * Counts occurrences of word patterns across all novels.
     */
    public static void countWords() {
        HashMap<String, Integer> totalCounts = new HashMap<>();

        for (String novel : getNovelNames()) {
            String fileName = novel + "_wc.txt";
            try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split("\\|");
                    String pattern = parts[0];
                    int count = Integer.parseInt(parts[1]);
                    totalCounts.put(pattern, totalCounts.getOrDefault(pattern, 0) + count);
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        for (String pattern : totalCounts.keySet()) {
            System.out.println(pattern + ": " + totalCounts.get(pattern));
        }
    }

    /**
     * Returns an array of novel names.
     *
     * @return An array of novel names.
     */
    private static String[] getNovelNames() {
        return new String[]{"Frankenstein", "Dracula", "Dr_Jekyll_and_Mr_Hyde", "The_Picture_of_Dorian_Gray", "The_Turn_of_the_Screw", "The_Castle_of_Otranto"};
    }

    /**
     * Main method to run the program.
     *
     * @param args Command-line arguments (not used).
     */
    public static void main(String[] args) {
        countWords();
    }
}